apiVersion: v1
kind: Pod
metadata:
  name: myapp
spec:
  containers:
  - name: frontend
    image: ozgurozturknet/k8s:blue
    ports:
    - containerPort: 80
    livenessProbe:
      httpGet:
        path: /healthcheck
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5
    volumeMounts:
      - name:  depo
        mountPath:  /klasor1
  - name: sidecar
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "sleep 3600"]
    volumeMounts:
      - name:  depo
        mountPath:  /klasor2
  volumes:
    - name:  depo
      emptyDir: {}
        