---
- name: DB Configuration
  hosts: db_server
  tasks:
  - name: Install the latest version of MariaDB & PyMySQL
    become: yes
    ansible.builtin.yum:
      name:
        - mariadb-server
        - python3-PyMySQL
      state: latest

  # - name: Start Mariadb server
  #   become: yes
  #   ansible.builtin.shell: systemctl start mariadb

  - name: Start & enable service mariadb
    become: yes
    ansible.builtin.service:
      name: mariadb
      state: started
      enabled: yes
  
  - name: Copy initial db to the server
    ansible.builtin.copy:
      src: /home/ec2-user/project/db-load-script.sql
      dest: ~/ 
  
  # - name: Set root password
  #   mysql_user:
  #     login_password: ''
  #     login_user: root
  #     name: root
  #     password: "clarus1234"
  ## Bu kismi bir kere calistirdiktan sonra login_password duzeltilmeli . cunku giris sifresi degisti
  - name: Copy .my.cnf file to db_server
    ansible.builtin.copy:
      src: /home/ec2-user/project/.my.cnf
      dest: ~/ 
  
  - name: Create database user with password and all database privileges and 'WITH GRANT OPTION'
    community.mysql.mysql_user:
      name: remoteUser
      password: "clarus1234"
      priv: '*.*:ALL,GRANT'
      state: present
      # login_user: root
      # login_password: "clarus1234"
      host: "{{ hostvars['web_server'].ansible_host }}"
    
  - name: Create a new database with name ecomdb
    mysql_db:
      name:
        - ecomdb
      state: present
      # login_user: root
      # login_password: "clarus1234"
  
  - name: check if ecomdb has table
    shell: |
      echo "USE ecomdb; show tables like 'products'; " | mysql
    register: resultOfShowTables

  - name: Print return information from resultOfShowTables
    ansible.builtin.debug:
      var: resultOfShowTables

  - name: Create database table
    community.mysql.mysql_db:
      name: ecomdb
      state: import
      target: ~/db-load-script.sql
    when: resultOfShowTables.stdout == ""
  
  - name: Restart service mariadb
    become: yes
    ansible.builtin.service:
      name: mariadb
      state: restarted

- name: WebServer Configuration
  hosts: web_server
  become: yes
  tasks:
  - name: Install a list of packages to my server
    become: yes
    package:
      name:
        - git
        - httpd
        - php
        - php-mysqlnd
      state: present
  - name: Make sure a service unit is running
    ansible.builtin.systemd:
      state: started
      name: httpd
      enabled: yes

  - name: clone the repo to web_server
    shell: |
      if [ -z "$(ls -al /var/www/html | grep .git)" ]; then
        git clone https://github.com/kodekloudhub/learning-app-ecommerce.git /var/www/html/
        echo "ok"
      else
        echo "already cloned..."
      fi
    register: result

  - name: See the result of clone tasks
    debug:
      var: result
  - name: Fix mysql connect command in index.php
    lineinfile:
      path: /var/www/html/index.php
      regexp: '172.20.1.101'
      line: "$link = mysqli_connect('{{ hostvars['db_server'].ansible_host }}', 'remoteUser', 'clarus1234', 'ecomdb');"
    when: not result.stdout == "already cloned..."
  - name: Disable Selinux
    selinux:
      state: disabled    

  - name: Restart apache service 
    service:
      name: httpd
      state: restarted  
    ## alternative
    # systemd:
    #   name: httpd
    #   state: restarted 

