- name: windows server configuration
  hosts: windows_servers
  tasks:  
    - name: Set timezone to 'Greenland Standard Time' 
      community.windows.win_timezone:
        timezone: Greenland Standard Time

    - name: Change the hostname to webserver
      win_hostname:
        name: ansible-hostname
      register: res # yapilan islemlerin sonucu res degiskenine ataniyor
    
    - name: See the result
      debug:
        var: res  

    - name: Reboot
      win_reboot:
      when: res.reboot_required
        

- name: Ping to linux server
  hosts: linux_servers
  tasks:
  -  name: Check the connectivity for linux server
     ping: 