apiVersion: v1
kind: Pod
metadata:
  name: first-pod
  labels:
    lab: etiket1
spec:
  containers:
    - name: nginx-pod
      image: nginx
      ports:
        - containerPort: 80
      resources:
        