apiVersion: apps/v1
kind: Deployment
metadata:
  name: configmap
spec:
  replicas: 2
  selector:
    matchLabels:
      app: configmap
  template:
    metadata:
      labels:
        app: configmap
    spec:
      containers:
      - name: deneme
        image: clarusway/demo:hello-config-env
        ports:
        - containerPort: 8888
        env:
          - name: GREETING
            value: Hallo
