apiVersion: apps/v1
kind: Deployment
metadata:
  name: env-config
spec:
  selector:
    matchLabels:
      app: env-config
  template:
    metadata:
      labels:
        app: env-config
    spec:
      containers:
      - name: kapsayici
        image: clarusway/demo:hello-config-env
        env:
          - name: GREETING
            valueFrom:
              configMapKeyRef:
                name: myconfigmap-demo
                key: greeting
        ports:
        - containerPort: 8888
