apiVersion: v1
kind: Service
metadata:
  name: myservice
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 8888
    nodePort: 30006
  selector:
    etiket: deploy-etiket  #servisin selectoru her zaman pod'un label'ina bakar
