apiVersion: v1
kind: Service   
metadata:
  name: web-flask-svc
  labels:
    app: web-flask
spec:
  type: NodePort  
  ports:
  - port: 3000  
    nodePort: 30333
    targetPort: 5000
  selector:
    app: web-flask