apiVersion: apps/v1 
kind: Deployment 
metadata:
  name: web-flask-deploy
spec:
  replicas: 3 
  selector:  
    matchLabels:
      app: web-flask
  minReadySeconds: 10 # pod hazir olana kadar 10 sn'ye bekle
  strategy: # deploymetni version icin kullaniliriz asil amac olarak.1-Recreate2-RollingUpdate adinda iki method var
    type: RollingUpdate 
    rollingUpdate:
      maxUnavailable: 1  #maximum guncelleme sirasinda bir tane calismayan pod olsun 10% sekilde de belirtebiliriz.ilk pod guncellenen pod ayaga kalkar sonra eski rs belirtilen oranda podu unavailable yapar
      maxSurge: 1        # maximum desired olarak belirtilen pod sayisindan ne kadar fazla sistemde pod olabilecegini belirten kisim
  template:              # 100 pod olusacaksa 25% secmissem sistemde maximum 125 pod olabilir ayakta ayni anda 25 tane de siler.25 ayaga kalkar 25 tane siler
    metadata:           # production ortaminda genellikle bu tercih edilir
      labels:
        app: web-flask
    spec:
      containers:
      - name: web-flask-pod
        image: clarusway/cw_web_flask1
        ports:
        - containerPort: 5000