apiVersion: v1
kind: Pod
metadata:
  name: pod-deneme-2
  labels:
    app: myapp
spec:
  containers:
  - name: apache
    image: httpd
    ports:
      - containerPort: 80
        name: "http"
    volumeMounts:
      - mountPath: "/usr/local/apache2/htdocs"
        name: depom
  volumes:
    - name: depom
      persistentVolumeClaim:
        claimName: pvc-6gb