apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod1
spec:
  containers:
  - name: nodeaffinity1
    image: ozgurozturknet/k8s
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution: # alttaki tanima gore bir node bul yoksa node olusturulmasin.eslesme mutlaka olmasi lazim
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: In #In, NotIn(anti affinity demek), Exists(burada sadece key girerim degerin bir onemi yok demek,app olsunda degeri onemli degil)
            values:      #DoesNotExist(ustunde app anahtari olmayan bir node)
            - blue
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod2
spec:
  containers:
  - name: nodeaffinity2
    image: ozgurozturknet/k8s
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution: # tanima bak buna uygun bie node bul ,bulamazsan herhangi birinde olustur
      - weight: 1 # hangisi daha oncelikli oldugunu ifade etmek icin
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - blue
      - weight: 2 # oncelik burada sunku 2 1'den buyuk
        preference:
          matchExpressions:
          - key: app
            operator: In
            values:
            - red
---
apiVersion: v1
kind: Pod
metadata:
  name: nodeaffinitypod3
spec:
  containers:
  - name: nodeaffinity3
    image: ozgurozturknet/k8s
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: app
            operator: Exists #In, NotIn, Exists, DoesNotExist