---
- name: update web servers
  hosts: webservers
  remote_user: root
  tasks:
    - name: ensure apache is at the latest version
      yum:
        name: httpd
        state: latest
    - name: write the apache config file
      template:
        src: /srv/httpd.j2
        dest: /etc/httpd.cfg

- name: copy for linux
  hosts: webservers
  tasks:
    - name: Copy your file to the webservers
      copy:
        src: /home/ec2-user/testfile1
        dest: /home/ec2-user/testfile1

- name: update db servers
  hosts: databases
  remote_user: root
  tasks:
    - name: ensure postgresql is at the latest version
      yum:
        name: psotgresql
        state: latest
    - name: write that postgresql is started
      template:
        name: postgresql
        state: started
    
    