apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-deneme
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/home/ubuntu/pv-data"