apiVersion: v1
kind: Pod
metadata:
  name: myPod 
  labels:
    name: myapp
spec:
  containers:
  - name: myContainer
    image: redis
    env:
      - name: USERNAME
        valueFrom:
          secretKeyRef:
            name: secretobjem
            key: username
      - name: PASSWORD
        valueFrom:
          secretKeyRef:
            name: secretobjem
            key: password
  restartPolicy: Never
