apiVersion: v1
kind: Pod
metadata:
  name: myPod
  labels:
    name: myapp
spec:
  containers:
  - name: myContainer
    image: redis
    env:
      - name: SECRET_USERNAME 
        value: mehmet
      - name: SECRET_PASSWORD
        value: fdlkjsfhlk123
  restartPolicy: Never
