- name: Create users from a list
  hosts: "*"
  become: yes
  tasks:
  - name: Add several users if OS is Redhat
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop:
    - joe
    - matt
    - james
    - oliver
    when: ansible_os_family == "RedHat"
  - name: Add several users if OS is Suse
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop:
    - david
    - tyler
    when: ansible_os_family == "Suse"
  - name: Add several users if OS is Debian & Ansible ver. is 20.04
    ansible.builtin.user:
      name: "{{ item }}"
      state: present
    loop:
    - john
    - aaron
    when: ansible_os_family == "Debian" and ansible_distribution_version == "20.04"