- name: Apache installation to Amz Linux 2 servers
  hosts: webservers
  tasks:
  - name: Install the latest version of Apache
    become: yes
    ansible.builtin.yum:
      name: httpd
      state: latest
  
  - name: start Apache service
    become: yes
    shell: "service httpd start"
  
  # - name: Start service httpd, if not started
  #   ansible.builtin.service:
  #     name: httpd
  #     state: started
  #     enabled: yes

- name: Apache installation to Amz Ubuntu servers
  hosts: ubuntuservers
  become: yes
  tasks:
  - name: make a system update
    ansible.builtin.shell: "apt update -y"
  - name: Install apache httpd  (state=present is optional)
    ansible.builtin.apt:
      name: apache2
      state: present
  - name: Start service httpd, if not started
    ansible.builtin.service:
      name: apache2
      state: started