- name: Create a User
  become: true
  hosts: all
  vars_files:
    - secret.yaml
  tasks:
    - name: create-User
      user:
        name: "{{ username }}"
        password:  "{{ password }}"

#  a node1 -b -m shell -a "cat /etc/shadow | tail -n1 "
# a node1 -b -m shell -a " grep tyler /etc/shadow "