- name: Create User-1
  become: yes
  vars_files: secret1.yaml
  hosts: "*"
  tasks:
    - name: Creating User
      user:
        name: "{{ username }}"
        password: "{{ pwhash | password_hash ('sha512') }}"

    - debug:
        msg: "Username is {{ username | upper }}"