- name: show facts
  hosts: all
  tasks:
    - name: showing facts
      ansible.builtin.debug:
        var: ansible_facts
    - name: Hostname  
      debug: #setup or garter_facts
        var: ansible_facts["hostname"] # bu sekilde yazildiginda  ansible_hostname yazmaya gerek yok
     
    - shell: 'ls -al'
      register: result

    - debug:
        var: result.stdout_lines
