apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 5000         # bu service'in dinleyecegi port
      targetPort: 5000   # podlarin expose ettigi port