- name: create a user using a variable
  hosts: all
  become: true
  vars:
    user: mehmet
  tasks:
    - name: create a user {{ user }}
      user:
        name: "{{ user }}"

    - debug:
        msg: "private ip is {{ foo }}"

    - debug:
        msg: "instance id is {{ boo }}"

    - debug:
        msg: "my key file is {{ key }}"

    - debug: 
        msg: "host is  {{ ansible_host }}"